import argparse
import os
import os.path as osp

import mmcv
import numpy as np
from nuscenes.utils.data_classes import RadarPointCloud
from PIL import Image, ImageDraw
from pyquaternion import Quaternion


def parse_args():
    parser = argparse.ArgumentParser(
        description='Export nuScenes radar/map/trajectory samples.')
    parser.add_argument(
        '--info',
        default='data/nuscenes/nuscenes_map_infos_temporal_train.pkl',
        help='nuScenes map info pkl generated by custom_nusc_map_converter.py')
    parser.add_argument(
        '--out-dir',
        default='work_dirs/nuscenes_radar_map_samples',
        help='output directory')
    parser.add_argument('--start-index', type=int, default=0)
    parser.add_argument('--num-samples', type=int, default=8)
    parser.add_argument('--sweeps-num', type=int, default=10)
    parser.add_argument(
        '--pc-range',
        type=float,
        nargs=4,
        default=None,
        help='x_min y_min x_max y_max in LiDAR coordinates')
    parser.add_argument(
        '--patch-mode',
        choices=['frame', 'strip', 'block'],
        default='frame',
        help='patch organization mode; strip/block are inference-oriented')
    parser.add_argument(
        '--stride-m',
        type=float,
        default=0.0,
        help='sample anchors by traveled distance in meters; 0 keeps every frame')
    parser.add_argument(
        '--raw-xy',
        action='store_true',
        help='plot x as horizontal axis and y as vertical axis')
    parser.add_argument(
        '--image-size',
        type=int,
        nargs=2,
        default=[800, 600],
        metavar=('WIDTH', 'HEIGHT'),
        help='grayscale sample/label image size')
    parser.add_argument(
        '--skip-existing',
        action='store_true',
        help='reuse existing per-sample png/npz files when present')
    return parser.parse_args()


def lidar2global_matrix(info):
    lidar2ego = np.eye(4)
    lidar2ego[:3, :3] = Quaternion(
        info['lidar2ego_rotation']).rotation_matrix
    lidar2ego[:3, 3] = info['lidar2ego_translation']
    ego2global = np.eye(4)
    ego2global[:3, :3] = Quaternion(
        info['ego2global_rotation']).rotation_matrix
    ego2global[:3, 3] = info['ego2global_translation']
    return ego2global @ lidar2ego


def transform_points(points, transform):
    points_h = np.concatenate(
        [points[:, :3], np.ones((points.shape[0], 1))], axis=1)
    return (points_h @ transform.T)[:, :3]


def load_one_radar(radar_info, ref_ts, load_dim=6):
    RadarPointCloud.disable_filters()
    points_raw = RadarPointCloud.from_file(radar_info['data_path']).points.T
    points = np.zeros((points_raw.shape[0], load_dim), dtype=np.float32)
    if points_raw.shape[0] == 0:
        return points

    points[:, :3] = points_raw[:, :3]
    points[:, :3] = points[:, :3] @ radar_info['sensor2lidar_rotation'].T
    points[:, :3] += radar_info['sensor2lidar_translation']
    points[:, 3] = points_raw[:, 5]  # rcs
    points[:, 4] = np.linalg.norm(points_raw[:, 8:10], axis=1)
    points[:, 5] = ref_ts - radar_info['timestamp'] / 1e6
    return points


def load_radar_points(info, sweeps_num):
    if 'radars' not in info or len(info['radars']) == 0:
        raise KeyError(
            'Missing info["radars"]. Re-run custom_nusc_map_converter.py.')

    ref_ts = info['timestamp'] / 1e6
    points_list = []
    for radar_info in info['radars'].values():
        points_list.append(load_one_radar(radar_info, ref_ts))
        for sweep in radar_info.get('sweeps', [])[:sweeps_num]:
            points_list.append(load_one_radar(sweep, ref_ts))
    if len(points_list) == 0:
        return np.zeros((0, 6), dtype=np.float32)
    return np.concatenate(points_list, axis=0)


def build_trajectory(infos, index, traj_radius=80):
    cur_info = infos[index]
    cur_scene = cur_info['scene_token']
    cur_lidar2global = lidar2global_matrix(cur_info)
    global2cur_lidar = np.linalg.inv(cur_lidar2global)

    scene_indices = [
        i for i, item in enumerate(infos)
        if item['scene_token'] == cur_scene
        and abs(i - index) <= traj_radius
    ]
    scene_indices = sorted(scene_indices)
    global_points = []
    for i in scene_indices:
        global_points.append(infos[i]['ego2global_translation'])
    global_points = np.asarray(global_points, dtype=np.float32)
    if global_points.size == 0:
        return np.zeros((0, 3), dtype=np.float32)
    return transform_points(global_points, global2cur_lidar)


def ego_xy(info):
    return np.asarray(info['ego2global_translation'][:2], dtype=np.float32)


def select_indices_by_stride(infos, start, end, stride_m):
    indices = []
    last_scene = None
    last_xy = None
    traveled_since_last = 0.0
    for index in range(start, end):
        info = infos[index]
        scene = info['scene_token']
        cur_xy = ego_xy(info)
        if scene != last_scene:
            indices.append(index)
            last_scene = scene
            last_xy = cur_xy
            traveled_since_last = 0.0
            continue
        if last_xy is None:
            indices.append(index)
            last_xy = cur_xy
            continue
        step = float(np.linalg.norm(cur_xy - last_xy))
        traveled_since_last += step
        last_xy = cur_xy
        if stride_m <= 0 or traveled_since_last >= stride_m:
            indices.append(index)
            traveled_since_last = 0.0
    return indices


def clip_points(points, pc_range):
    x_min, y_min, x_max, y_max = pc_range
    mask = (
        (points[:, 0] >= x_min) & (points[:, 0] <= x_max) &
        (points[:, 1] >= y_min) & (points[:, 1] <= y_max)
    )
    return points[mask]


def project_xy(points, raw_xy=False):
    if len(points) == 0:
        return np.zeros((0, 2), dtype=np.float32)
    if raw_xy:
        return points[:, [0, 1]]
    return points[:, [1, 0]]


def setup_axes(ax, pc_range, raw_xy=False):
    x_min, y_min, x_max, y_max = pc_range
    if raw_xy:
        ax.set_xlim(x_min, x_max)
        ax.set_ylim(y_min, y_max)
    else:
        ax.set_xlim(y_min, y_max)
        ax.set_ylim(x_min, x_max)
    ax.set_aspect('equal', adjustable='box')
    ax.grid(color='#eeeeee', linewidth=0.8)
    ax.set_xticks([])
    ax.set_yticks([])


def get_display_range(pc_range, raw_xy=False):
    x_min, y_min, x_max, y_max = pc_range
    if raw_xy:
        return x_min, x_max, y_min, y_max
    return y_min, y_max, x_min, x_max


def points_to_pixels(points, pc_range, image_size, raw_xy=False):
    width, height = image_size
    pts = project_xy(points, raw_xy)
    if len(pts) == 0:
        return np.zeros((0, 2), dtype=np.int32)

    disp_x_min, disp_x_max, disp_y_min, disp_y_max = get_display_range(
        pc_range, raw_xy)
    u = (pts[:, 0] - disp_x_min) / (disp_x_max - disp_x_min)
    v = (disp_y_max - pts[:, 1]) / (disp_y_max - disp_y_min)
    pixels = np.stack([u * (width - 1), v * (height - 1)], axis=1)
    return np.round(pixels).astype(np.int32)


def draw_points(draw, points, pc_range, image_size, raw_xy, fill, radius=1):
    pixels = points_to_pixels(points, pc_range, image_size, raw_xy)
    width, height = image_size
    for x, y in pixels:
        if x < 0 or x >= width or y < 0 or y >= height:
            continue
        draw.ellipse(
            (x - radius, y - radius, x + radius, y + radius),
            fill=fill)


def draw_lines(draw, lines, pc_range, image_size, raw_xy, fill, width=2):
    for line in lines:
        line = np.asarray(line)
        if line.ndim != 2 or line.shape[0] < 2:
            continue
        pixels = points_to_pixels(line, pc_range, image_size, raw_xy)
        if len(pixels) < 2:
            continue
        draw.line([tuple(point) for point in pixels], fill=fill, width=width)


def save_sample_label_pair(sample_name, out_dir, image_size, pc_range, raw_xy,
                           radar_points, trajectory, dividers, boundaries):
    samples_dir = osp.join(out_dir, 'samples')
    labels_dir = osp.join(out_dir, 'labels')
    os.makedirs(samples_dir, exist_ok=True)
    os.makedirs(labels_dir, exist_ok=True)

    sample_img = Image.new('L', tuple(image_size), 255)
    sample_draw = ImageDraw.Draw(sample_img)
    draw_points(
        sample_draw, radar_points, pc_range, image_size, raw_xy,
        fill=0, radius=1)
    draw_lines(
        sample_draw, dividers, pc_range, image_size, raw_xy,
        fill=80, width=2)
    draw_lines(
        sample_draw, [trajectory], pc_range, image_size, raw_xy,
        fill=150, width=3)
    draw_points(
        sample_draw, np.array([[0.0, 0.0, 0.0]], dtype=np.float32),
        pc_range, image_size, raw_xy, fill=200, radius=4)
    sample_img.save(osp.join(samples_dir, f'{sample_name}.png'))

    label_img = Image.new('L', tuple(image_size), 0)
    label_draw = ImageDraw.Draw(label_img)
    draw_lines(
        label_draw, boundaries, pc_range, image_size, raw_xy,
        fill=255, width=3)
    label_img.save(osp.join(labels_dir, f'{sample_name}.png'))


def lines_to_list(lines):
    return [np.asarray(line, dtype=float).tolist() for line in lines]


def local_lines_to_global(lines, lidar2global):
    global_lines = []
    for line in lines:
        line = np.asarray(line, dtype=np.float32)
        if line.ndim != 2 or line.shape[0] == 0:
            continue
        points = np.zeros((line.shape[0], 3), dtype=np.float32)
        points[:, :2] = line[:, :2]
        global_lines.append(transform_points(points, lidar2global)[:, :2])
    return global_lines


def annotation_to_global(annotation, lidar2global):
    return {
        key: local_lines_to_global(value, lidar2global)
        for key, value in annotation.items()
    }


def plot_lines(ax, lines, color, linewidth, raw_xy=False, alpha=1.0):
    for line in lines:
        line = np.asarray(line)
        if line.ndim != 2 or line.shape[0] < 2:
            continue
        pts = project_xy(line, raw_xy)
        ax.plot(
            pts[:, 0], pts[:, 1],
            color=color,
            linewidth=linewidth,
            alpha=alpha,
            marker='.',
            markersize=2)


def save_sample(info, infos, index, out_dir, sweeps_num, pc_range, raw_xy,
                image_size, skip_existing=False, patch_mode='frame',
                patch_order=0, stride_m=0.0):
    import matplotlib.pyplot as plt

    radar_points = clip_points(load_radar_points(info, sweeps_num), pc_range)
    trajectory = clip_points(build_trajectory(infos, index), pc_range)
    annotation = info['annotation']
    lidar2global = lidar2global_matrix(info)
    global_annotation = annotation_to_global(annotation, lidar2global)
    dividers = annotation.get('divider', [])
    boundaries = annotation.get('boundary', [])

    fig, ax = plt.subplots(figsize=(14, 8), dpi=160)
    setup_axes(ax, pc_range, raw_xy)

    radar_xy = project_xy(radar_points, raw_xy)
    if len(radar_xy) > 0:
        ax.scatter(
            radar_xy[:, 0], radar_xy[:, 1],
            s=2,
            c='black',
            alpha=0.70,
            linewidths=0,
            label='radar points')

    plot_lines(ax, boundaries, color='#444444', linewidth=1.0,
               raw_xy=raw_xy, alpha=0.35)
    plot_lines(ax, dividers, color='#2b83c6', linewidth=1.5,
               raw_xy=raw_xy, alpha=0.85)

    traj_xy = project_xy(trajectory, raw_xy)
    if len(traj_xy) > 0:
        ax.plot(
            traj_xy[:, 0], traj_xy[:, 1],
            color='red',
            linewidth=2.0,
            marker='o',
            markersize=2.5,
            label='ego trajectory')

    ego_xy = project_xy(np.array([[0.0, 0.0, 0.0]], dtype=np.float32), raw_xy)
    ax.scatter(
        ego_xy[:, 0], ego_xy[:, 1],
        s=120,
        c='#ff2d75',
        marker='^',
        edgecolors='white',
        linewidths=0.8,
        zorder=10)

    sample_name = f'{patch_order:04d}_{patch_mode}_{index:04d}_{info["token"][:8]}'
    check_path = osp.join(out_dir, f'{sample_name}.png')
    npz_path = osp.join(out_dir, f'{sample_name}.npz')
    sample_path = osp.join(out_dir, 'samples', f'{sample_name}.png')
    label_path = osp.join(out_dir, 'labels', f'{sample_name}.png')
    outputs_exist = (
        osp.exists(check_path) and osp.exists(npz_path) and
        osp.exists(sample_path) and osp.exists(label_path))
    if not (skip_existing and outputs_exist):
        save_sample_label_pair(
            sample_name, out_dir, image_size, pc_range, raw_xy, radar_points,
            trajectory, dividers, boundaries)

        fig.tight_layout(pad=0.1)
        fig.savefig(check_path)

        np.savez_compressed(
            npz_path,
            radar_points=radar_points,
            trajectory=trajectory,
            dividers=np.array(dividers, dtype=object),
            boundaries=np.array(boundaries, dtype=object),
            lidar2global=lidar2global,
            token=info['token'],
            scene_token=info['scene_token'])
    plt.close(fig)
    raster_info = dict(
        sample_name=sample_name,
        token=info['token'],
        scene_token=info['scene_token'],
        timestamp=info['timestamp'],
        bev_img_path=sample_path,
        boundary_label_path=label_path,
        check_img_path=check_path,
        source_npz_path=npz_path,
        pc_range=list(pc_range),
        image_size=list(image_size),
        raw_xy=raw_xy,
        patch_mode=patch_mode,
        patch_order=patch_order,
        anchor_index=index,
        stride_m=float(stride_m),
        map_location=info.get('map_location', None),
        lidar2global=lidar2global.astype(float).tolist(),
        ego2global_translation=info.get('ego2global_translation', None),
        ego2global_rotation=info.get('ego2global_rotation', None),
        lidar2ego_translation=info.get('lidar2ego_translation', None),
        lidar2ego_rotation=info.get('lidar2ego_rotation', None),
        annotation=annotation,
        global_annotation=global_annotation,
        raster_annotation={
            key: lines_to_list(value)
            for key, value in annotation.items()
        },
        global_raster_annotation={
            key: lines_to_list(value)
            for key, value in global_annotation.items()
        })
    return raster_info


def main():
    args = parse_args()
    os.makedirs(args.out_dir, exist_ok=True)
    data = mmcv.load(args.info)
    infos = sorted(data['infos'], key=lambda item: item['timestamp'])

    if args.pc_range is not None:
        pc_range = list(args.pc_range)
    elif args.patch_mode == 'strip':
        pc_range = [-10.0, -40.0, 110.0, 40.0]
    elif args.patch_mode == 'block':
        pc_range = [-60.0, -60.0, 60.0, 60.0]
    else:
        pc_range = [-30.0, -40.0, 30.0, 40.0]

    end = min(args.start_index + args.num_samples, len(infos))
    selected_indices = select_indices_by_stride(
        infos, args.start_index, end, args.stride_m)
    raster_infos = []
    for patch_order, index in enumerate(mmcv.track_iter_progress(selected_indices)):
        raster_infos.append(save_sample(
            infos[index], infos, index, args.out_dir, args.sweeps_num,
            pc_range, args.raw_xy, args.image_size,
            skip_existing=args.skip_existing,
            patch_mode=args.patch_mode,
            patch_order=patch_order,
            stride_m=args.stride_m))
    raster_data = dict(
        infos=raster_infos,
        metadata=dict(
            source_info=args.info,
            pc_range=list(pc_range),
            image_size=list(args.image_size),
            raw_xy=args.raw_xy,
            sweeps_num=args.sweeps_num,
            patch_mode=args.patch_mode,
            stride_m=float(args.stride_m),
            map_classes=['divider', 'ped_crossing', 'boundary', 'centerline']))
    mmcv.dump(raster_data, osp.join(args.out_dir, 'maptr_raster_infos.pkl'))
    json_infos = []
    for item in raster_infos:
        json_item = item.copy()
        json_item.pop('annotation')
        json_item.pop('global_annotation')
        json_infos.append(json_item)
    mmcv.dump(
        dict(infos=json_infos, metadata=raster_data['metadata']),
        osp.join(args.out_dir, 'maptr_raster_infos.json'))
    print(f'Exported {len(raster_infos)} samples to {args.out_dir}')


if __name__ == '__main__':
    main()
